### ISSUE TITLE
Assets Catalog for PDF

### ISSUE THREAD

**Issue by samirGuerdah** [AliSoftware/OHPDFImage#12]
Hello,

You have mentioned in the Readme file that adding a pdf image in the assets catalog (Xcode6) is not a good practice. Is it still the case for Xcode 7 ?

**Comment by AliSoftware** [comment]
I never said in the README that it's not a good practice.

I just said that you should not put PDF in the Assets Catalog… if you want them to use them as vector images at runtime with `OHPDFImage`.

It's totally fine to create an image set with a PDF in your Assets Catalogs. But if you do that, then Xcode will _generate PNG files at compile time_ and you will have bitmap images in your app bundle once compiled; so the vector image will not be kept and the end result will be the same as if you creates PNG files for `@1x`, `@2x` and `@3x` resolutions. In fact, that's exactly what Xcode did for you during the compilation phase: transform your PDF into the various PNG resolutions.

So if you want to use `OHPDFImage`, whose purpose is to manipulate vector images that are still in their vector format after compilation and not rasterized as PNG, so that you can scale them at runtime without any loss, you don't want Xcode to convert your PDF to PNG files at compile time, that's why you don't want to add them as image sets in your Assets Catalogs (but you can add them as standard resources, either in the resources copy phase, or add them as data sets)

**Comment by samirGuerdah** [comment]
I have misunderstood the README file. Thanks for your answer.
